package com.a.rxjavaapp

data class UserBean(
    var avatar_url: String?,
    var bio: Any?,
    var blog: String?,
    var company: Any?,
    var created_at: String?,
    var email: Any?,
    var events_url: String?,
    var followers: Int?,
    var followers_url: String?,
    var following: Int?,
    var following_url: String?,
    var gists_url: String?,
    var gravatar_id: String?,
    var hireable: Any?,
    var html_url: String?,
    var id: Int?,
    var location: Any?,
    var login: String?,
    var name: String?,
    var node_id: String?,
    var organizations_url: String?,
    var public_gists: Int?,
    var public_repos: Int?,
    var received_events_url: String?,
    var repos_url: String?,
    var site_admin: Boolean?,
    var starred_url: String?,
    var subscriptions_url: String?,
    var twitter_username: Any?,
    var type: String?,
    var updated_at: String?,
    var url: String?
)